filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
set_display_intro_string ("Good Afternoon Mark! Welcome to Bandicoot version 0.1.4.7")
use_graphics_interface_state ()
use_graphics_interface_state ()
filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
stereo_mode_state ()
save_state ()
