(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-display-intro-string "Good Afternoon Mark! Welcome to Bandicoot version 0.1.4.7")
(use-graphics-interface-state)
(use-graphics-interface-state)
(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(stereo-mode-state)
(save-state)
