# These commands are the saved state of coot.  You can evaluate them
# using "Calculate->Run Script...".
set_graphics_window_size(500, 500)
set_graphics_window_position(0, 0)
vt_surface(2)
set_clipping_front(0.00)
set_clipping_back(0.00)
set_map_radius(16.00)
set_iso_level_increment(0.0500)
set_diff_map_iso_level_increment(0.0050)
set_colour_map_rotation_on_read_pdb(21.00)
set_colour_map_rotation_on_read_pdb_flag(1)
set_colour_map_rotation_on_read_pdb_c_only_flag(1)
set_swap_difference_map_colours(0)
set_background_colour(0.00, 0.00, 0.00)
set_symmetry_size(13.00)
set_symmetry_colour_merge(0.50)
set_symmetry_colour(0.10, 0.20, 0.80)
set_symmetry_atom_labels_expanded(0)
set_active_map_drag_flag(1)
set_show_aniso(0)
set_aniso_probability(50.00)
set_smooth_scroll_steps(40)
set_smooth_scroll_limit(10.00)
set_font_size(2)
set_rotation_centre_size(0.10)
set_do_anti_aliasing(0)
set_default_bond_thickness(5)
set_map_sampling_rate(1.80)
set_matrix(60.00)
set_show_symmetry_master(0)
set_go_to_atom_molecule(0)
set_zoom(100.00)
set_rotation_centre(0.00, 0.00, 0.00)
