#!/usr/bin/env python3
# -*- coding: ascii -*-
"""
bandicoot_backend.py -- a clean, reusable driver for the native Coot engine
(Bandicoot 0.1.4.8) that PyKekoMCP can use exactly the way it drives Moorhen
through run_js / moorhen_eval.

WHAT THIS IS
------------
BandicootBackend starts a headless Bandicoot process (`coot --no-graphics`),
opens a control channel to it, and exposes a single synchronous primitive:

    backend.eval("read_pdb('foo.pdb')")  ->  0

plus a handful of convenience verb methods (load_coordinates, go_to_residue,
mutate, residue_name, get_atom_count, ...) that map common PyKekoMCP verbs onto
Coot Python. `eval` is the direct analog of Moorhen `moorhen_eval` / `run_js`:
it ships a chunk of Python to the live engine and returns the value.

HOW THE CONTROL CHANNEL WORKS (and the traps it hides)
------------------------------------------------------
Bandicoot ships Coot's classic `remote_control.py`. Its protocol is inverted
from what you'd expect: WE run a TCP server, and Coot connects OUT to us as a
client. On connect Coot sends the banner line `Coot listener socket ready!`.
After that we send newline-separated Python lines, terminated by a line `# end`.
Coot's reader `listen_coot_listener_socket(soc)` reads until `# end`, then
`eval()`s each line (falling back to `exec()` on SyntaxError) and sends back
`return value: <repr>` per line. The line `# close` ends the session.

Four traps, all handled inside this module:

  (1) The import name inside Coot is `remote_control`, NOT `coot.remote_control`
      -- `coot` is a flat module. (Handled in the bundled coot-side script.)

  (2) The Coot wrapper mangles argv, so the port cannot be passed on the command
      line. We pass it through the environment variable COOT_CTRL_PORT instead.

  (3) The reader eval/execs inside `remote_control`'s own namespace, where the
      Coot API (read_pdb, mutate, ...) is NOT defined -> every command would
      NameError. The coot-side script injects the whole `coot` API into
      remote_control.__dict__ before entering the pump.

  (4) THE PUMP GAP. The built-in idle pump (run_python_thread / a gi GObject
      main loop) is DEAD in Bandicoot -- there is no `gi`. So nothing drives the
      socket by itself. The coot-side script therefore runs a manual blocking
      loop `while alive: alive = listen_coot_listener_socket(soc); sleep(0.02)`
      after opening the socket. This pumps the channel fully headless, no GUI /
      XQuartz required. Because the loop blocks Coot's main thread, the child
      NEVER exits on its own after `# close`; shutdown() must always terminate()
      the child process.

ROBUSTNESS / CONCURRENCY NOTES
------------------------------
  * KEEP IT SYNCHRONOUS. The reader accumulates into a module global
    `total_socket_data` that it treats as a list during recv and then
    reassigns to a joined str -- interleaving two outstanding batches corrupts
    that state. This backend serialises every eval() under a lock and keeps at
    most one batch outstanding.

  * recv(1024) CHUNKING. The reader recv()s in 1024-byte chunks and re-splits on
    `# end`. Keep any single command line modest (well under ~1 KB). For large
    payloads (e.g. writing a file), have Coot pull from disk rather than pushing
    bytes down the wire.

  * REPLY FRAMING. Replies are `"return value: " + str(ret)` with NO trailing
    newline, so consecutive replies concatenate. We split on the literal
    `return value:` marker. n_atoms(imol) returns 0 in a headless (non-drawn)
    molecule, so get_atom_count() writes the model to a temp PDB and counts
    ATOM/HETATM records for the truth.

  * LATENCY. The reader sleeps 0.1 s inside its recv loop, which dominates
    per-round-trip latency (~0.1-0.2 s on loopback). It is a control plane, not
    a hot path.

PYKEKOMCP INTEGRATION SKETCH
----------------------------
See the module-level string PYKEKOMCP_INTEGRATION below, or bandicoot_backend
--integration-sketch. In short: register a thin adapter tool group whose
`run_python` / `eval` tool calls BandicootBackend.eval(), mirroring the Moorhen
adapter's run_js -> moorhen_eval. That gives Claude one control plane addressing
both the Moorhen (browser/WASM) engine and the native Coot engine.
"""

import ast
import os
import re
import socket
import subprocess
import sys
import tempfile
import threading
import time

DEFAULT_COOT = "/Applications/bandicoot-0.1.4.8/bin/coot"
_RETURN_MARKER = "return value:"

# The coot-side pump script, bundled here so the backend is a single file.
# It is written to a temp path at start() and passed to `coot --script`.
# ASCII only. Handles traps (1), (3), (4) above; trap (2) is the env var it reads.
_COOT_SIDE_SCRIPT = r'''# Auto-generated by bandicoot_backend.py -- coot-side control pump.
# Runs INSIDE bandicoot via: coot --no-graphics --script <thisfile>
import sys, time, os
sys.stderr.write("COOT_SIDE: starting\n"); sys.stderr.flush()

import coot
import remote_control as rc

# TRAP (3): the reader eval/execs inside remote_control's namespace, where the
# coot API is not defined. Inject the whole coot module surface into rc so that
# socket commands resolve exactly as they would at the coot prompt.
for _name in dir(coot):
    if not _name.startswith("__"):
        try:
            setattr(rc, _name, getattr(coot, _name))
        except Exception:
            pass
rc.coot = coot

# TRAP (2): port arrives via env var, not argv (the wrapper mangles argv).
PORT = int(os.environ.get("COOT_CTRL_PORT", "0"))
HOST = os.environ.get("COOT_CTRL_HOST", "127.0.0.1")

# Coot connects OUT to our server and sends the ready banner. This also tries
# run_python_thread, which NameErrors harmlessly (the idle pump is dead here).
rc.open_coot_listener_socket(PORT, HOST)

soc = rc.coot_listener_socket
if not soc:
    sys.stderr.write("COOT_SIDE: FAILED to connect to server on port %s\n" % PORT)
    sys.stderr.flush()
    sys.exit(1)

sys.stderr.write("COOT_SIDE: connected, entering manual pump loop\n"); sys.stderr.flush()

# TRAP (4): the built-in idle pump is dead. Drive the socket manually. Each
# listen_coot_listener_socket() consumes one '# end'-terminated batch, evals or
# execs every line, and sends 'return value:' replies. Returns False on '# close'
# or when the server goes away.
alive = True
while alive:
    try:
        alive = rc.listen_coot_listener_socket(soc)
    except Exception as e:
        sys.stderr.write("COOT_SIDE: pump exception %r\n" % (e,)); sys.stderr.flush()
        break
    time.sleep(0.02)

sys.stderr.write("COOT_SIDE: pump ended\n"); sys.stderr.flush()
try:
    soc.close()
except Exception:
    pass
'''


PYKEKOMCP_INTEGRATION = r"""
PyKekoMCP integration sketch
============================

PyKekoMCP today exposes a Moorhen tool surface: moorhen_load_coordinates,
moorhen_go_to_residue, moorhen_run_js / moorhen_eval, etc. Each Moorhen tool is
a thin adapter that ultimately funnels arbitrary code through moorhen_eval
(run_js) into the browser/WASM Moorhen engine.

BandicootBackend is the native-Coot analog of that engine. To let Claude address
the native Coot engine from the same control plane, add a sibling adapter that
routes an equivalent tool surface to BandicootBackend:

    # pykekomcp/bandicoot_adapter.py  (sketch)
    from bandicoot.bandicoot_backend import BandicootBackend

    _backend = None
    def _get():
        global _backend
        if _backend is None:
            _backend = BandicootBackend()
            _backend.start()
        return _backend

    # The core primitive -- the exact analog of moorhen_eval / run_js.
    @tool("coot_eval")
    def coot_eval(code: str):
        return _get().eval(code)

    # Verb tools mirror the Moorhen ones 1:1 so the model uses one mental model.
    @tool("coot_load_coordinates")
    def coot_load_coordinates(path: str):
        return _get().load_coordinates(path)     # -> imol

    @tool("coot_go_to_residue")
    def coot_go_to_residue(chain: str, resno: int, imol: int = 0):
        return _get().go_to_residue(chain, resno, imol=imol)

    @tool("coot_mutate")
    def coot_mutate(chain: str, resno: int, restype: str, imol: int = 0):
        return _get().mutate(chain, resno, restype, imol=imol)

    @tool("coot_get_atom_count")
    def coot_get_atom_count(imol: int = 0):
        return _get().get_atom_count(imol)

    # Lifecycle wiring: heartbeat for health checks, shutdown on server stop.
    @tool("coot_health")
    def coot_health():
        return _get().healthy()

Registration in the MCP server is symmetric with Moorhen: expose the tool group,
lazily start the backend on first use, and call shutdown() from the server's
teardown / atexit hook. Because BandicootBackend.eval is synchronous and
serialised, the adapter needs no extra locking. Naming stays engine-prefixed
(coot_* vs moorhen_*) so a single Claude session can drive both engines and keep
them straight.
"""


class BandicootBackendError(RuntimeError):
    pass


class BandicootBackend(object):
    """Synchronous control channel to a headless Bandicoot (native Coot) process.

    Usage:
        b = BandicootBackend()
        b.start()
        imol = b.load_coordinates("/path/to/model.pdb")
        b.mutate("A", 25, "ALA", imol=imol)
        b.shutdown()

    Every public call is serialised under a lock; keep at most one batch
    outstanding (see module docstring, "KEEP IT SYNCHRONOUS").
    """

    def __init__(self, coot_bin=DEFAULT_COOT, host="127.0.0.1",
                 accept_timeout=90.0, reply_timeout=30.0, scratch_dir=None):
        self.coot_bin = coot_bin
        self.host = host
        self.accept_timeout = accept_timeout
        self.reply_timeout = reply_timeout
        self.scratch_dir = scratch_dir or tempfile.gettempdir()

        self._srv = None
        self._conn = None
        self._proc = None
        self._coot_side_path = None
        self._stderr_log = None
        self._lock = threading.Lock()
        self._started = False

    # -- lifecycle -----------------------------------------------------------

    def start(self):
        """Bind an ephemeral localhost port, spawn headless coot, accept its
        connection, and read the ready banner. Raises on failure."""
        if self._started:
            return
        if not os.path.exists(self.coot_bin):
            raise BandicootBackendError("coot binary not found: %s" % self.coot_bin)

        # Bind an ephemeral port (port 0 -> OS picks a free one).
        srv = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        srv.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        srv.bind((self.host, 0))
        srv.listen(1)
        srv.settimeout(self.accept_timeout)
        port = srv.getsockname()[1]
        self._srv = srv

        # Write the bundled coot-side pump script to a temp file.
        fd, path = tempfile.mkstemp(prefix="bandicoot_coot_side_",
                                    suffix=".py", dir=self.scratch_dir)
        with os.fdopen(fd, "w") as fh:
            fh.write(_COOT_SIDE_SCRIPT)
        self._coot_side_path = path

        # Child stderr goes to a log so pump diagnostics survive.
        self._stderr_log = os.path.join(
            self.scratch_dir, "bandicoot_coot_stderr_%d.log" % port)
        err_fh = open(self._stderr_log, "w")

        env = dict(os.environ)
        env["COOT_CTRL_PORT"] = str(port)      # TRAP (2): port via env, not argv
        env["COOT_CTRL_HOST"] = self.host

        self._proc = subprocess.Popen(
            [self.coot_bin, "--no-graphics", "--script", path],
            stdout=subprocess.DEVNULL,
            stderr=err_fh,
            env=env,
        )

        try:
            conn, _addr = srv.accept()
        except socket.timeout:
            self._cleanup_after_failure()
            raise BandicootBackendError(
                "coot did not connect within %.0fs (see %s)"
                % (self.accept_timeout, self._stderr_log))
        conn.settimeout(self.reply_timeout)
        self._conn = conn

        # First line from coot is the ready banner.
        banner = self._read_line(conn)
        if "Coot listener socket ready" not in banner:
            self._cleanup_after_failure()
            raise BandicootBackendError("unexpected banner: %r" % banner)

        self._started = True
        return port

    def shutdown(self):
        """Send '# close' then ALWAYS terminate the child (it has no auto-pump
        and blocks in the manual loop, so it never self-exits)."""
        if self._conn is not None:
            try:
                self._conn.sendall(b"# close\n# end\n")
                time.sleep(0.3)
            except Exception:
                pass
            try:
                self._conn.close()
            except Exception:
                pass
            self._conn = None

        if self._srv is not None:
            try:
                self._srv.close()
            except Exception:
                pass
            self._srv = None

        # Trap (4): the child blocks in the manual pump -> always terminate it.
        if self._proc is not None:
            try:
                self._proc.terminate()
                self._proc.wait(timeout=5)
            except Exception:
                try:
                    self._proc.kill()
                except Exception:
                    pass
            self._proc = None

        if self._coot_side_path and os.path.exists(self._coot_side_path):
            try:
                os.remove(self._coot_side_path)
            except Exception:
                pass
            self._coot_side_path = None

        self._started = False

    def _cleanup_after_failure(self):
        try:
            self.shutdown()
        except Exception:
            pass

    def __enter__(self):
        self.start()
        return self

    def __exit__(self, *exc):
        self.shutdown()

    # -- core primitive ------------------------------------------------------

    def eval(self, code_str, wait=None):
        """Send one line of Python to the live Coot engine and return the parsed
        value. The direct analog of Moorhen run_js / moorhen_eval.

        `code_str` should be a single expression or statement (one logical line;
        the reader eval()s then exec()s each newline-separated line separately).
        Keep it modest in size (recv(1024) chunking). Serialised under a lock so
        only one batch is ever outstanding.
        """
        if not self._started or self._conn is None:
            raise BandicootBackendError("backend not started")
        wait = self.reply_timeout if wait is None else wait

        with self._lock:
            payload = (code_str + "\n# end\n").encode()
            self._conn.sendall(payload)
            reply = self._read_reply(self._conn, wait)
        return _parse_return_value(reply)

    def eval_raw(self, code_str, wait=None):
        """Like eval() but returns the raw 'return value: ...' text, unparsed.
        Useful for debugging or when the repr should not be coerced."""
        if not self._started or self._conn is None:
            raise BandicootBackendError("backend not started")
        wait = self.reply_timeout if wait is None else wait
        with self._lock:
            self._conn.sendall((code_str + "\n# end\n").encode())
            return self._read_reply(self._conn, wait)

    def healthy(self):
        """Heartbeat: send 1+1, expect 2. Returns True/False, never raises."""
        try:
            return self.eval("1+1", wait=10) == 2
        except Exception:
            return False

    # -- convenience verbs (map PyKekoMCP verbs -> Coot Python) ---------------

    def load_coordinates(self, path):
        """read_pdb(path) -> imol (the new molecule index)."""
        path = os.path.abspath(os.path.expanduser(path))
        if not os.path.exists(path):
            raise BandicootBackendError("no such file: %s" % path)
        return self.eval('read_pdb(%r)' % path)

    def go_to_residue(self, chain, resno, imol=0, ins=""):
        """Centre the view on a residue's CA-ish position via set_go_to_atom.
        Falls back gracefully; returns the coot status int."""
        self.eval('set_go_to_atom_molecule(%d)' % imol)
        return self.eval('set_go_to_atom_chain_residue_atom_name(%r, %d, " CA ")'
                         % (chain, int(resno)))

    def set_rotation_centre(self, x, y, z):
        """set_rotation_centre(x, y, z)."""
        return self.eval('set_rotation_centre(%r, %r, %r)'
                         % (float(x), float(y), float(z)))

    def get_rotation_centre(self):
        """Read back the current rotation centre as (x, y, z) floats."""
        x = self.eval('rotation_centre_position(0)')
        y = self.eval('rotation_centre_position(1)')
        z = self.eval('rotation_centre_position(2)')
        return (x, y, z)

    def residue_name(self, chain, resno, imol=0, ins=""):
        """residue_name(imol, chain, resno, ins) -> 3-letter code (or None)."""
        return self.eval('coot.residue_name(%d, %r, %d, %r)'
                         % (imol, chain, int(resno), ins))

    def mutate(self, chain, resno, restype, imol=0, ins=""):
        """mutate(imol, chain, resno, ins, restype). Persists in the live model;
        confirm with residue_name() afterward."""
        return self.eval('mutate(%d, %r, %d, %r, %r)'
                         % (imol, chain, int(resno), ins, restype))

    def write_pdb(self, imol, out_path):
        """write_pdb_file(imol, out_path) -> status. Ground truth for headless
        molecules (n_atoms returns 0 when nothing is drawn)."""
        out_path = os.path.abspath(os.path.expanduser(out_path))
        return self.eval('write_pdb_file(%d, %r)' % (imol, out_path))

    def get_atom_count(self, imol=0):
        """Truthful atom count: write the model to a temp PDB and count
        ATOM/HETATM records. n_atoms(imol) is unreliable headless (returns 0)."""
        fd, tmp = tempfile.mkstemp(prefix="bandicoot_count_", suffix=".pdb",
                                   dir=self.scratch_dir)
        os.close(fd)
        try:
            self.write_pdb(imol, tmp)
            # Give the write a beat to flush.
            deadline = time.time() + 5.0
            while time.time() < deadline:
                if os.path.exists(tmp) and os.path.getsize(tmp) > 0:
                    break
                time.sleep(0.05)
            n = 0
            with open(tmp, "r") as fh:
                for line in fh:
                    if line.startswith("ATOM") or line.startswith("HETATM"):
                        n += 1
            return n
        finally:
            try:
                os.remove(tmp)
            except Exception:
                pass

    # -- socket plumbing -----------------------------------------------------

    @staticmethod
    def _read_line(conn):
        """Read until the first newline (for the banner)."""
        buf = b""
        while b"\n" not in buf:
            chunk = conn.recv(1024)
            if not chunk:
                break
            buf += chunk
        return buf.decode("utf-8", errors="replace").strip()

    def _read_reply(self, conn, wait):
        """Collect the 'return value:' reply(s) for one batch.

        Framing insight: for our 'CODE\n# end\n' payload the reader eval/execs
        TWO lines -- the CODE line (real value) and the empty line before '# end'
        (execs to None) -- so a complete batch reply always contains at least
        TWO 'return value:' markers, the second being the terminal '...None'.
        We can therefore stop as soon as the second marker arrives instead of
        draining on a fixed timer, which keeps round-trips near the reader's own
        0.1 s recv cadence rather than that plus a fixed mop-up window.
        """
        conn.settimeout(wait)
        got = b""
        marker = _RETURN_MARKER.encode()
        t0 = time.time()
        while got.count(marker) < 2:
            try:
                chunk = conn.recv(4096)
            except socket.timeout:
                break
            if not chunk:
                break
            got += chunk
            if time.time() - t0 > wait:
                break
        # Brief mop-up: catch any trailing bytes of the terminal reply that
        # arrived split across the marker boundary. Short and only when needed.
        if got.count(marker) >= 2:
            conn.settimeout(0.05)
            try:
                while True:
                    chunk = conn.recv(4096)
                    if not chunk:
                        break
                    got += chunk
            except socket.timeout:
                pass
        conn.settimeout(self.reply_timeout)
        return got.decode("utf-8", errors="replace")


def _parse_return_value(text):
    """Extract the value from a 'return value: <repr>' reply.

    The reader emits ONE reply per newline-separated line it eval/execs. Our
    payload is 'CODE\n# end\n', so the reader sees the CODE line (real value)
    AND a trailing empty line that exec()s to None -> two concatenated replies:
        'return value: <value>return value: None'
    We therefore take the FIRST reply's value, not the last (the last is the
    empty-line None). Coerce to int/float/None when the repr is a clean literal;
    otherwise return the stripped string.
    """
    if _RETURN_MARKER not in text:
        return text.strip()
    # First segment after the first marker, up to the next marker (if any).
    after_first = text.split(_RETURN_MARKER, 1)[1]
    tail = after_first.split(_RETURN_MARKER, 1)[0].strip()
    # Try to coerce simple literals (ints, floats, None, True/False, tuples).
    try:
        return ast.literal_eval(tail)
    except Exception:
        pass
    # Coot often returns bare numbers without quotes.
    if re.fullmatch(r"-?\d+", tail):
        return int(tail)
    if re.fullmatch(r"-?\d+\.\d+(e-?\d+)?", tail, re.IGNORECASE):
        return float(tail)
    if tail == "None":
        return None
    return tail


# ---------------------------------------------------------------------------
# Self-test: a realistic multi-command session in ONE live coot process.
# Run:  python3 bandicoot_backend.py [PDB]
# ---------------------------------------------------------------------------

def _selftest(pdb_path):
    print("=" * 68)
    print("BandicootBackend self-test (fully headless, --no-graphics)")
    print("=" * 68)
    b = BandicootBackend()
    port = b.start()
    print("[start] server port=%d, coot pid=%d, banner OK"
          % (port, b._proc.pid))
    print("[start] DISPLAY env = %r (headless, no XQuartz)"
          % os.environ.get("DISPLAY"))

    try:
        # 1. load coordinates
        imol = b.load_coordinates(pdb_path)
        print("\n>>> load_coordinates(%s)" % pdb_path)
        print("    <<< imol = %r" % imol)

        # 2. atom count via write-back (n_atoms is unreliable headless)
        n_direct = b.eval('n_atoms(%d)' % imol)
        n_true = b.get_atom_count(imol)
        print("\n>>> n_atoms(%d)  [headless, unreliable]" % imol)
        print("    <<< %r" % n_direct)
        print(">>> get_atom_count(%d)  [write-back truth]" % imol)
        print("    <<< %r atoms" % n_true)

        # 3. set rotation centre and read it back
        print("\n>>> set_rotation_centre(11.0, 22.0, 33.0)")
        print("    <<< %r" % b.set_rotation_centre(11.0, 22.0, 33.0))
        rc = b.get_rotation_centre()
        print(">>> get_rotation_centre()")
        print("    <<< (%.3f, %.3f, %.3f)" % (rc[0], rc[1], rc[2]))

        # 4. go to residue
        print("\n>>> go_to_residue('A', 25)")
        print("    <<< status = %r" % b.go_to_residue("A", 25, imol=imol))

        # 5. LIVE MUTATION: residue_name before -> mutate -> residue_name after
        before = b.residue_name("A", 25, imol=imol)
        print("\n>>> residue_name('A', 25)  [before]")
        print("    <<< %r" % before)
        print(">>> mutate('A', 25, 'ALA')")
        print("    <<< status = %r" % b.mutate("A", 25, "ALA", imol=imol))
        after = b.residue_name("A", 25, imol=imol)
        print(">>> residue_name('A', 25)  [after]")
        print("    <<< %r" % after)
        mutation_ok = (before != after and after == "ALA")
        print("    ==> live mutation persisted: %s (%r -> %r)"
              % (mutation_ok, before, after))

        # 6. heartbeat
        print("\n>>> healthy()  [heartbeat 1+1==2]")
        print("    <<< %r" % b.healthy())

        # 7. latency: average over several tight round-trips
        N = 8
        t0 = time.time()
        for _ in range(N):
            b.eval("1+1")
        per = (time.time() - t0) / N * 1000.0
        print("\n>>> latency: %d x eval('1+1')" % N)
        print("    <<< ~%.1f ms / round-trip" % per)

        print("\n" + "=" * 68)
        print("RESULT: mutation_ok=%s  heartbeat=%s  latency=%.1fms  headless=%s"
              % (mutation_ok, b.healthy(), per, os.environ.get("DISPLAY") is None))
        print("=" * 68)
    finally:
        b.shutdown()
        print("[shutdown] '# close' sent, child terminated, sockets closed")


def main(argv):
    if "--integration-sketch" in argv:
        print(PYKEKOMCP_INTEGRATION)
        return 0
    default_pdb = os.path.expanduser(
        "~/xtal/lig_test/non_covalent/3PTB/3PTB.pdb")
    pdb = default_pdb
    for a in argv[1:]:
        if not a.startswith("-"):
            pdb = a
    _selftest(pdb)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
